[feature]-[10}-[semver:minor]-Headbar tasarımı gerçekleştirildi. Inpu…
bimser-intern/todosaurus pull request #11
Opened 2022-04-07 13:29 UTC by Uyetiskin

…t aktif edilmedi.

2022-04-08 07:11 UTC, otipirdamaz requested changes

2022-04-08 07:11 UTC, otipirdamaz commented on src/components/Headbar.js
> +                    <a href='http://localhost:3001/' className='mt-2 ml-12 h-6 '>
localhost:3001 bu değerlerin bu şekilde hardcoded olmaması lazım. Ana sayfaya gidilmek isteniyorsa url belirtmeden yönlendirmenin yöntemleri araştırılmalı

2022-04-08 07:11 UTC, otipirdamaz commented on src/components/Headbar.js
> +                        href='http://localhost:3001/'
localhost:3001 bu değerlerin bu şekilde hardcoded olmaması lazım. Ana sayfaya gidilmek isteniyorsa url belirtmeden yönlendirmenin yöntemleri araştırılmalı

2022-04-08 11:40 UTC, Uyetiskin commented on src/components/Headbar.js
> +                    <a href='http://localhost:3001/' className='mt-2 ml-12 h-6 '>
Biraz araştırdıktan sonra parent component içerisinde çağırdığımız componentleri bu şekilde yönlendirebiliriz.
```
function App(){
  return (
      <>
           <Collapse href='firstCategories' >
                <Card />   //Card componenti Collapse componentinin childıdır.
           </Collapse>
     </>
}
function Collapse(props){
 
return(
     <>
         <a href={"#".concat(props.href)} />
        <div id={props.href} >
              {props.children}       //Burada collapse componenti olan Card componentini alırız.
       </> 

     </>
}

2022-04-08 13:31 UTC, otipirdamaz commented on src/components/Headbar.js
> +                    <a href='http://localhost:3001/' className='mt-2 ml-12 h-6 '>
react-router kütüphanesini araştırabilirsin

2022-04-11 08:46 UTC, otipirdamaz approved these changes

2022-04-11 08:46 UTC, merged